version: '3'
services:
  nginx_proxy:
    build:
      context: .
      dockerfile: staging.dockerfile
    env_file:
      - .staging.env
    ports:
      - 8080:${NGINX_PORT1}
      - 8443:${NGINX_PORT2}
      - ${NODE_PORT}:${NODE_PORT}
    extra_hosts:
     - ${EXTERNAL_HOST}:${EXTERNAL_IP}

